////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated. 
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace CoffeeCove.AdminSite
//{


//    public partial class SignIn
//    {

//        /// <summary>
//        /// adminUsername2 control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.TextBox adminUsername2;

//        /// <summary>
//        /// adminUsername2_rqdValidator control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.RequiredFieldValidator adminUsername2_rqdValidator;

//        /// <summary>
//        /// adminUsername2_regexValidator control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.RegularExpressionValidator adminUsername2_regexValidator;

//        /// <summary>
//        /// adminPassword2 control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.TextBox adminPassword2;

//        /// <summary>
//        /// adminPassword2_rqdValidator control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.RequiredFieldValidator adminPassword2_rqdValidator;

//        /// <summary>
//        /// adminPassword2_regexValidator control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.RegularExpressionValidator adminPassword2_regexValidator;

//        /// <summary>
//        /// forgotPasswordLink control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.HyperLink forgotPasswordLink;

//        /// <summary>
//        /// signIn_btn control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button signIn_btn;
//    }
//}
