////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated. 
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace CoffeeCove.AdminSite
//{


//    public partial class SignUp
//    {

//        /// <summary>
//        /// adminUsername control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.TextBox adminUsername;

//        /// <summary>
//        /// adminUsername_rqdValidator control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.RequiredFieldValidator adminUsername_rqdValidator;

//        /// <summary>
//        /// adminUsername_regexValidator control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.RegularExpressionValidator adminUsername_regexValidator;

//        /// <summary>
//        /// adminPassword control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.TextBox adminPassword;

//        /// <summary>
//        /// adminPassword_rqdValidator control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.RequiredFieldValidator adminPassword_rqdValidator;

//        /// <summary>
//        /// adminPassword_regexValidator control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.RegularExpressionValidator adminPassword_regexValidator;

//        /// <summary>
//        /// adminPassReenter control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.TextBox adminPassReenter;

//        /// <summary>
//        /// adminPassReenter_rqdValidator control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.RequiredFieldValidator adminPassReenter_rqdValidator;

//        /// <summary>
//        /// reenterAdminPassword_compareValidator control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.CompareValidator reenterAdminPassword_compareValidator;

//        /// <summary>
//        /// adminGender control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.RadioButtonList adminGender;

//        /// <summary>
//        /// gender_rqdValidator control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.RequiredFieldValidator gender_rqdValidator;

//        /// <summary>
//        /// location control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.DropDownList location;

//        /// <summary>
//        /// location_rqdValidator control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.RequiredFieldValidator location_rqdValidator;

//        /// <summary>
//        /// signUp_btn control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button signUp_btn;
//    }
//}
