//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeCove
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Nullable<int> cusID { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string HashedPassword { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string ContactNo { get; set; }
        public string Gender { get; set; }
        public string ResidenceState { get; set; }
        public string ProfilePicturePath { get; set; }
    }
}
