//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeCove
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int DeliveryNo { get; set; }
        public string DeliveryDate { get; set; }
        public string DeliveryTime { get; set; }
        public string AddressLine { get; set; }
        public string Unit { get; set; }
        public string Level { get; set; }
        public string PostCode { get; set; }
        public string DeliveryStatus { get; set; }
    }
}
