//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeCove
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string CustomerID { get; set; }
        public string PickUpNo { get; set; }
        public string DeliveryNo { get; set; }
        public string OrderDate { get; set; }
        public string TotalAmount { get; set; }
    }
}
