//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeCove
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickUp
    {
        public int PickUpNo { get; set; }
        public int StoreID { get; set; }
        public string PickUpDate { get; set; }
        public string PickUpTime { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
