//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeCove
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int RatingReviewID { get; set; }
        public int RatingScore { get; set; }
        public string ReviewContent { get; set; }
        public System.DateTime RatingReviewDateTime { get; set; }
        public int PaymentID { get; set; }
        public Nullable<int> CusID { get; set; }
        public Nullable<int> ReplyTo { get; set; }
        public string UsernameAdmin { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual PaymentDetail PaymentDetail { get; set; }
    }
}
